[package]
name = "tanzil"
version = "0.0.1"
authors = ["Hatim Thayyil <hatim@thayyil.net>"]
edition = "2021"
description = "Tanzil"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
